// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUMiHgh8dOUyl977JqsWfAQcHQGHx2Xso',
    appId: '1:997291290470:web:becb9e9da049d7f92da2a7',
    messagingSenderId: '997291290470',
    projectId: 'auto-aid-b9f9a',
    authDomain: 'auto-aid-b9f9a.firebaseapp.com',
    storageBucket: 'auto-aid-b9f9a.firebasestorage.app',
    measurementId: 'G-LZJ9HKX3HG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYAR9QOLUreitD8kdbopsV4pMGHG9WgWA',
    appId: '1:997291290470:android:0bbf925afdf505d62da2a7',
    messagingSenderId: '997291290470',
    projectId: 'auto-aid-b9f9a',
    storageBucket: 'auto-aid-b9f9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH-rae7czTJKdBRkdnD8eXCpHAqiIebVk',
    appId: '1:997291290470:ios:d8ed64a3df0020d42da2a7',
    messagingSenderId: '997291290470',
    projectId: 'auto-aid-b9f9a',
    storageBucket: 'auto-aid-b9f9a.firebasestorage.app',
    iosClientId: '997291290470-e1jtvlhcq10g7e35uomm8mctka0p1ntg.apps.googleusercontent.com',
    iosBundleId: 'com.example.autoMobileChatbot',
  );
}
